### ISSUE TITLE
load_root_certificates()

### ISSUE THREAD

**Issue by LukasB-DEV** [hoels/app-store-server-library-php#3]
Hello,

thats not realy an issue but could you provide an example for load_root_certificates()?

BR
Lukas

**Comment by hoels** [comment]
Hey Lukas, first you should download all root certificates from the "Apple Root Certificates" section on the [Apple PKI](https://www.apple.com/certificateauthority/) website. If you store all certificates in an `/apple-root-certificates/` folder, your function could look something like this:

```php
/**
 * @return string[]
 * @throws Exception
 */
function loadRootCertificates(): array
{
    $rootCertificates = [];
    $certificatesDir = __DIR__ . "/apple-root-certificates";
    if (($files = scandir($certificatesDir)) !== false) {
        foreach ($files as $file) {
            if (str_ends_with($file, ".cer")
                && ($content = file_get_contents($certificatesDir . "/" . $file)) !== false
            ) {
                $rootCertificates[] = $content;
            }
        }
    }

    if (empty($rootCertificates)) {
        throw new Exception("No Apple root certificates found.");
    }

    return $rootCertificates;
}
```

Make sure to provide the correct directory containing the certificates, and implement proper error handling.
