### ISSUE TITLE
PHP Fatal error in ReceiptUtility.php

### ISSUE THREAD

**Issue by Filavision** [hoels/app-store-server-library-php#5]
Hey!

When i pass an invalid receipt (for example delete one sign of the receipt), i got this PHP Fatal error:

`AH01071: Got error 'PHP message: PHP Fatal error: Uncaught ValueError in /var/www/vhosts/my.app/httpdocs/lib/app-store-server-library-php/src/AppStoreServerLibrary/ReceiptUtility.php:32\nStack trace:\n#0 /var/www/vhosts/my.app/httpdocs/inc/test.php(36): AppStoreServerLibrary\\ReceiptUtility->extractTransactionIdFromAppReceipt()\n#1 {main}\n thrown in /var/www/vhosts/my.app/httpdocs/lib/app-store-server-library-php/src/AppStoreServerLibrary/ReceiptUtility.php on line 32'`

Code on test.php line 36 is:

`$transactionId = $receiptUtility->extractTransactionIdFromAppReceipt($appReceipt);`

**Comment by hoels** [comment]
Hey Steven,
the `ValueError` is expected and intentionally thrown in line 32 of the `ReceiptUtility`. After all, it's invalid data you are passing to the method.
