### ISSUE TITLE
Blank array while verify certificate 

### ISSUE THREAD

**Issue by tarikalalwani** [hoels/app-store-server-library-php#7]
2nd issue , i am facing is getting blank array in below 2 variables in **Class Name :** ChainVerifier , **Method** : verify

1. leafCertificate
 [openSSLPublicKey:AppStoreServerLibrary\X509\Certificate:private] => OpenSSLAsymmetricKey Object
        (
        )

2. intermediateCertificate
[openSSLPublicKey:AppStoreServerLibrary\X509\Certificate:private] => OpenSSLAsymmetricKey Object
        (
        )

**Comment by tarikalalwani** [comment]
$publicKey = $this->verifyChain(
            leafCertificate: $leafCertificate,
            intermediateCertificate: $intermediateCertificate,
            performOnlineChecks: $performOnlineChecks,
            effectiveDate: $effectiveDate
        );

getting blank public key. Can u please help me resolve issue

**Comment by hoels** [comment]
I am not sure what your goal is here and I also can't help without knowing the specific error. I'm just wondering why you are directly using the `ChainVerifier`. The `ChainVerifier` is more or less an internal class that is used by the `SignedDataVerifier` and not intended to be interacted with. All you need to do is to configure and use the `SignedDataVerifier` in the way explained in the [README](https://github.com/hoels/app-store-server-library-php?tab=readme-ov-file#verification-usage). If that doesn't work, there's most likely an issue with how you provide the array of root certificates.

**Comment by tarikalalwani** [comment]
I have solved the issue. thanks for your resposnse. But when i tried to upload on server.php version created issue. php version on server is 7.4.3 and library needed php 8.1

**Comment by hoels** [comment]
Yes, PHP 8.1 brought many useful new language features like enums and readonly properties used in the library. In addition, older versions do not receive security updates anymore. For that reason, I made 8.1 a requirement.

**Comment by tarikalalwani** [comment]
As my project is developed in php 7.4 , i have converted library to support the php version

**Comment by hoels** [comment]
For security reasons, I would recommend to reconsider this. There haven‘t been too many deprecations since 7.4, so your project is most likely compatible with 8.1 as well. If you can, better try to keep your PHP and library versions up-to-date.
